import { Metadata } from 'next';

import Footer from '@/components/Footer';

 // Import but only render client-side
import '@fontsource/manrope';
import '@fontsource/inter';
import '@fontsource/lato';
import '@fontsource/italianno';
import './globals.css';
import SplashWrapper from '@/components/SplashWrapper';

export const metadata: Metadata = {
  title: 'Nishat | Premium Clothing Brand',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Splash screen state ko manage karne ke liye hum client component banayenge

  // Yahan hum client component nahi use kar sakte (kyunki ye server component hai)
  // isliye splash screen ko ClientWrapper component mein handle karenge

  return (
    <html lang="en">
      <body className="data-scroll-container min-h-screen m-0 p-0 antialiased">
      
          <SplashWrapper>{children}</SplashWrapper>
       
        <Footer />
      </body>
    </html>
  );
}
